config/routes.rb
SampleApp::Application.routes.draw do
  root to: 'static_pages#home'

  resources :users
  resources :books
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/doc', to: 'static_pages#doc'

end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id           :integer          not null, primary key
#  title        :string(255)
#  author       :string(255)
#  publisher    :string(255)
#  release_date :date
#  n_pages      :integer
#  image_url    :string(255)
#  isbn         :string(255)
#  description  :text
#  user_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Book < ActiveRecord::Base
  attr_accessible :author,
                  :title,
                  :publisher,
                  :release_date,
                  :n_pages,
                  :image_url,
                  :isbn,
                  :description
                  :user_id

  belongs_to :user

  validates :user_id, presence: true
  validates :title,  presence: true, length: { maximum: 100 }
  validates :author,  presence: true, length: { maximum: 50 }
  validates :publisher,  presence: true, length: { maximum: 100 }
  validates :image_url,  presence: true
  validates :isbn, presence: true, length: { minimum: 13, maximum: 13 }
  validates :description,  presence: true
 # validates_uniqueness_of :isbn

  default_scope order: 'books.created_at DESC'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  remember_token  :string(255)
#  admin           :boolean          default(FALSE)
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  has_many :books, dependent: :destroy

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name,  presence: true,
                    length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  validates :password, presence: true,
                       length: { minimum: 6 }

  validates :password_confirmation, presence: true
  after_validation { self.errors.messages.delete(:password_digest) }

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  # Force signout to prevent CSRF attacks
  def handle_unverified_request
    sign_out
    super
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_filter :signed_in_user

  def new
    @book = Book.new
  end

  def create
    @book = current_user.books.build(params[:book])
    if @book.save
      flash[:success] = "Book created correctly, check it out in the books catalog!"
      redirect_to root_url
    else
      render 'books/new'
    end
  end

  def show
    @book = Book.find(params[:id])

  end

  def edit
     @book = Book.find(params[:id])
  end













  def update
    @book = Book.find(params[:id])

    if @book.update_attributes(params[:book])
      flash[:success] = "Book updated"
      redirect_to @book
    else
      render 'edit'
    end
  end

  def destroy
    Book.find(params[:id]).destroy
    flash[:success] = "Book destroyed."
    redirect_to root_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @books = Book.paginate(page: params[:page], :per_page => 6, :order => 'created_at DESC')
  end

  def doc
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_filter :signed_in_user, only: [:index, :edit, :update]
before_filter :correct_user,   only: [:edit, :update]
before_filter :admin_user,     only: :destroy

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def index
  #  @users = User.paginate(page: params[:page], :per_page => 10)
    @users = User.paginate(page: params[:page], :per_page => 10, :order => 'name ASC')
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.paginate(page: params[:page], :per_page => 10)
    @books_count = @user.books.count
  end

  def new
    @user = User.new
  end

  def edit

  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Novels database"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def current_is_admin?
    if current_user
       current_user.admin?
    else
       false
    end
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/books/_book.html.erb
<li>
  <div class="imageinfo">
    <img src= "<%= book.image_url %>" width="300"/>
    <div class="timestamp">
      Posted <%= time_ago_in_words(book.created_at) %> ago</br>

<% if !current_user.nil? %>
      by <%= link_to User.find(book.user_id).name, User.find(book.user_id) %>
<% end %>
    </div>
    <% if current_user?(book.user) || current_is_admin? %>
      <p>

        <%= link_to "Delete", book, method: :delete,
                                    data: { confirm: "You sure?" },
                                    class: "btn btn-large btn-primary"  %>

        <%= link_to "Edit", edit_book_path(book),
                                    class: "btn btn-large btn-primary"  %>
      </p>
    <% end %>


  </div>

  <div>
      <div>
          <h3><%= book.title %></h3></br>
          <STRONG>Author: </STRONG><%= book.author %></br>
          <STRONG>Publisher: </STRONG><%= book.publisher %></br>
          <STRONG>Release date: </STRONG><%= book.release_date %></br>
          <STRONG>Pages count: </STRONG><%= book.n_pages %></br>
          <STRONG>ISBN: </STRONG><%= book.isbn %></br>
          <STRONG>Short description: </STRONG><pre><%= book.description %></pre>
      </div>

  </div>

  <div style="clear:both"></div>
</li>

app/views/books/edit.html.erb
<% provide(:title, 'New Book') %>
<h1>Edit your book</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@book) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :author %>
      <%= f.text_field :author %>

      <%= f.label :publisher %>
      <%= f.text_field :publisher %>

      <%= f.label :release_date %>
      <%= f.date_select(:release_date, options = { order: [:month, :day, :year], prompt: { month: 'Select Month', day: 'Select Day', year: 'Select Year' }, start_year: 1950 }, html_options = { size: 1 }) %>

      <%= f.label :n_pages %>
      <%= f.number_field :n_pages, :min => 1, :value => 1 %>

      <%= f.label :image_url %>
      <%= f.url_field :image_url %>

      <%= f.label :isbn %>
      <%= f.text_field :isbn %>

      <%= f.text_area :description, placeholder: "Insert book description here..." %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
      <%= link_to 'Back', "/", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/books/new.html.erb
<% provide(:title, 'New Book') %>
<h1>New Book</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@book) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :author %>
      <%= f.text_field :author %>

      <%= f.label :publisher %>
      <%= f.text_field :publisher %>

      <%= f.label :release_date %>
      <%= f.date_select(:release_date, options = { order: [:month, :day, :year], prompt: { month: 'Select Month', day: 'Select Day', year: 'Select Year' }, start_year: 1950 }, html_options = { size: 1 }) %>

      <%= f.label :n_pages %>
      <%= f.number_field :n_pages, :min => 1, :value => 1 %>

      <%= f.label :image_url %>
      <%= f.url_field :image_url %>

      <%= f.label :isbn %>
      <%= f.text_field :isbn %>

      <%= f.text_area :description, placeholder: "Insert book description here..." %>

      <%= f.submit "Create Book", class: "btn btn-large btn-primary" %>
      <%= link_to 'Back', "/", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/books/show.html.erb
<%= render @book %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
   <div>Autore: <a href="mailto:marco.gaiazzi.ggl@gmail.com">Marco Gaiazzi</a> 713906 </div>
   <div>Appello: Gennaio 2014 </div>

  </small>
  <nav>
    <ul>
      <li><%= link_to "Documentation",   doc_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "novels database", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Books", root_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Edit", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
   <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
     <!-- <%= debug(params) if Rails.env.development? %> -->
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_user_bar.html.erb
<div class="row">
    <aside class="span4">
      <section class="alignleftclass">
        <%= render 'shared/user_info' %>
      </section>
    </aside>

      <div class="pull-right">
        <%= link_to "New Book", new_book_path, class: "btn btn-large btn-primary" %>
      </div>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= pluralize(current_user.books.count, "book") %>
</span>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
    <h1>About Us</h1>
    <p>
      The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      is a project to make a book and screencasts to teach web development
      with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
      is the sample application for the tutorial.
    </p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
    <h1>Contact Us</h1>
    <p>
      Contact me on my <a href="https://www.facebook.com/marco.gaiazzi">Facebook page</a> or email me at: <a href="mailto:marco.gaiazzi.ggl@gmail.com">marco.gaiazzi.ggl@gmail.com</a>
    </p>

app/views/static_pages/doc.html.erb
<% provide(:title, 'Doc') %>
<h1>About...</h1>
<p>
<h3>Author's infos</h3>
<p>
      <div>Author: Marco Gaiazzi 713906</div>
      <div>University of Insubria (Varese)</div>
      <div>Email me at: <a href="mailto:marco.gaiazzi.ggl@gmail.com">marco.gaiazzi.ggl@gmail.com</a></div>
      <div>Or contact me on my <a href="https://www.facebook.com/marco.gaiazzi">Facebook page</a></div>
    </p>
<h3>Project description</h3>
<pre>
'NOVELS DATABASE' is a simple application that allows users perform actions regarding their's or other user's books depending they are logged in/out.

Non registered user: Can only browse available books on the main page.

Registered and logged in user: Can see post's owner and his user page displaying all of the books from that user.
Only the post owner can edit/delete his own posts.

Administrator: Same as a logged in user but can edit/delete others user's posts.

Users also have a "Gravatar" showing an avatar associated with their email at http://en.gravatar.com/

</pre>
<h3>Database informations</h3>
<pre>
The database comes prepared using custom tasks

Command used to prepare the database is

$ bundle exec rake db:prepare_database

You can also open a console and run the commands:

$ bundle exec rake db:reset
$ bundle exec rake db:populate

to test how the application behaves in presence of a high number of users and books

ADMIN login info ----> Name: 'marco.gaiazzi.ggl@gmail.com'
                       Password: 'administrator'

FAKE USERS login info ----> Name: 'fakemail-1@insubria.fake' (Change the number just before the '@')
                            Password: 'password'

# DATABASE
#
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  remember_token  :string(255)
#  admin           :boolean          default(FALSE)

# == Schema Information
#
# Table name: books
#
#  id           :integer          not null, primary key
#  title        :string(255)
#  author       :string(255)
#  publisher    :string(255)
#  release_date :date
#  n_pages      :integer
#  image_url    :string(255)
#  isbn         :string(255)
#  description  :text
#  user_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
</pre>
<h3>Assuming that...</h3>
<pre>
For practical reasons users are registered to the applications by a name(Nickname) and an email address which is used also as login information along with a password.
</pre>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
    <h1>Help</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
      To get help on this sample app, see the
      <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
    </p>

app/views/static_pages/home.html.erb
<% if signed_in? %>

<%= render 'shared/user_bar' %>

<% else %>
<div width="200">
  <div class="center hero-unit">

    <h3>Browse novels or upload your own!</h3>
    <div><%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %></div>
    <h5>Or check out <%= link_to "Documentation page", doc_path %> for more informations!</h5>

  </div>
</div>
<% end %>

<% if @books.any? %>
      <h1>Available Books</h1>
      <%= will_paginate @books %>
      <ul class="books">
        <%= render @books %>
      </ul>
      <%= will_paginate @books %>
<% else %>
      <h1>No books available...</h1>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>

</li>

app/views/users/create.html.erb
porcamadonnaladra

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

  <%= render 'shared/user_bar' %>

  <div>
    <% if @user.books.any? %>
      <h1><%= @user.name %>'s Books (<%= @books_count %>) </h1>
      <%= will_paginate @books %>
      <ol class="books">
        <%= render @books %>
      </ol>
      <%= will_paginate @books %>
    <% else %>
      <h3><%= @user.name %> still didn't insert any book </h3>
    <% end %>
  </div>